services:

  json_matcher.json_helper:
    class: Fesor\JsonMatcher\Helper\JsonHelper

  json_matcher.factory:
    class: Fesor\JsonMatcher\JsonMatcherFactory
    arguments: ['@json_matcher.json_helper', '%json_spec.excluded_keys%']

  json_spec.helper.memory_helper:
    class: JsonSpec\Behat\Helper\MemoryHelper

  json_spec.helper.json_loader:
    class: JsonSpec\JsonLoader
    arguments: ['%json_spec.json_directory%']

  json_spec.json_holder:
    class: JsonSpec\Behat\JsonProvider\JsonHolder

  json_spec.memory_helper_aware_initializer:
    class: JsonSpec\Behat\Context\Initializer\MemoryHelperAwareInitializer
    arguments: ['@json_spec.helper.memory_helper']
    tags:
      - {name: context.initializer}

  json_spec.json_holder_aware_initializer:
      class: JsonSpec\Behat\Context\Initializer\JsonHolderAwareInitializer
      arguments: ['@json_spec.json_holder']
      tags:
        - {name: context.initializer}

  json_spec.json_matcher_aware_initializer:
      class: JsonSpec\Behat\Context\Initializer\JsonMatcherAwareInitializer
      arguments: ['@json_matcher.factory']
      tags:
        - {name: context.initializer}

  json_spec.dependency_resolver:
    class: JsonSpec\Behat\Context\ArgumentResolver\DependencyResolver
    arguments:
     - '@json_matcher.factory'
     - '@json_spec.helper.json_loader'
     - '@json_matcher.json_helper'
    tags:
      - {name: context.argument_resolver}

  json_spec.context_class_resolver:
    class: JsonSpec\Behat\Context\ContextResolver\JsonSpecContextResolver
    tags:
      - {name: context.class_resolver}
